import { writeFileSync } from "node:fs";
import { join } from "node:path";
import { staticRedirectGroups } from "../src/data/redirects";
import { canonicalPostPath, canonicalPostSlug, derivedLegacyPostPath, readBlogMetadata } from "./content-utils";

type Redirect = { from: string; to: string };

function normalizePath(path: string) {
  return path.startsWith("/") ? path : `/${path}`;
}

const posts = readBlogMetadata();
const seenSlugs = new Map<string, string>();
const blogRedirects: Redirect[] = [];

for (const post of posts) {
  const slug = canonicalPostSlug(post);
  const existing = seenSlugs.get(slug);
  if (existing) throw new Error(`Blog slug collision for "${slug}": ${existing} and ${post.file}`);
  seenSlugs.set(slug, post.file);

  const to = canonicalPostPath(post);
  const legacySources = new Set<string>();
  legacySources.add(derivedLegacyPostPath(post));
  for (const legacyUrl of post.legacyUrls) legacySources.add(normalizePath(legacyUrl));
  if (legacySources.size === 0) throw new Error(`No legacy URL coverage for ${post.file}`);

  for (const from of legacySources) {
    if (from !== to) blogRedirects.push({ from, to });
  }
}

const sections = [
  ...staticRedirectGroups.map((group) => ({
    label: group.label,
    redirects: [...group.redirects].sort((a, b) => a.from.localeCompare(b.from)),
  })),
  { label: "Blog post redirects", redirects: blogRedirects.sort((a, b) => a.from.localeCompare(b.from)) },
];

const allSources = new Map<string, string>();
for (const section of sections) {
  for (const redirect of section.redirects) {
    if (allSources.has(redirect.from) && allSources.get(redirect.from) !== redirect.to) {
      throw new Error(`Conflicting redirect source ${redirect.from}: ${allSources.get(redirect.from)} vs ${redirect.to}`);
    }
    allSources.set(redirect.from, redirect.to);
  }
}

const lines = [
  "# Generated by scripts/generate-redirects.ts. Do not edit manually.",
  "",
  ...sections.flatMap((section) => [
    `# ${section.label}`,
    ...section.redirects.map((redirect) => `${redirect.from} ${redirect.to} 301`),
    "",
  ]),
];

writeFileSync(join(process.cwd(), "public/_redirects"), `${lines.join("\n").trimEnd()}\n`);
