// Hand-maintained event metadata for the poster archive.
//
// This file is NOT generated — edit it freely. The poster records themselves
// live in ./posters.ts, which IS generated by `pnpm posters:import`.
// Keeping them separate means regenerating posters never clobbers the prose
// written here.

export type PosterAuthor = {
  name: string;
  affiliation?: string;
};

export type Poster = {
  /**
   * Path segment for the canonical `/posters/<slug>/` page and the archive-local
   * `#poster-<slug>` anchor. Immutable once published — the importer preserves
   * it across title edits. See sourceUrl below.
   */
  slug: string;
  /** Matches a `PosterEvent.id` below. */
  event: string;
  posterNumber?: number;
  title: string;
  authors: PosterAuthor[];
  /** Plain text. Rendered as-is; no Markdown or HTML. */
  abstract: string;
  keywords?: string[];
  /**
   * The complete URL returned by Google Drive's "Copy link" action.
   * Some Drive links carry required query parameters or a resource key, so do
   * not reconstruct public URLs from a bare file ID.
   *
   * The importer extracts the Drive file ID from this URL and uses that ID —
   * not the URL text — as the stable poster identity for permalink
   * preservation, so a title correction never moves an existing URL.
   *
   * Corrections to the poster file itself must use Drive's "Manage versions →
   * Upload new version" on the existing file. Deleting and re-uploading mints a
   * new Drive ID, which reads here as a different poster.
   */
  sourceUrl: string;
  /**
   * Drive file ID extracted from sourceUrl by the importer.
   *
   * Two jobs: it is the stable identity used for permalink preservation, and
   * the page derives an optional thumbnail from it. That thumbnail endpoint is
   * undocumented and unsupported — see the comment in index.astro — so nothing
   * on the page may depend on the image loading.
   */
  driveFileId: string;
};

export type PosterEvent = {
  /** Anchor id, and the value matched against `Poster.event`. */
  id: string;
  label: string;
  /** Always the hyphenated event path; the unhyphenated form is a redirect source. */
  eventPath: string;
  dateLabel: string;
  blurb?: string;
};

export const posterEvents: PosterEvent[] = [
  {
    id: "defcon-34",
    label: "DEF CON 34",
    eventPath: "/events/defcon-34/",
    dateLabel: "August 6–9, 2026",
    blurb:
      "The inaugural AI Village poster track, themed Adversarial Attacks Against Agents and Agentic Systems.",
  },
];
